In [2]:
import pandas as pd
import numpy as np

In [3]:
restdf = pd.read_excel("Datos Restaurante-Copy1.xlsx")

In [4]:
restdf.head(5)

,Orden,Fecha,Hora de Cobro,Mesa,Atendió,Tipo,Producto,Categoria,Propina,Tipo de Cliente
0,1,2014-02-01,18:43:12,1,Rodolfo,Bebida,Tecate,Cervezas,0.07,Cliente Nuevo
1,1,2014-02-01,18:43:12,1,Rodolfo,Bebida,Tisana,Bebida no Alcohol,0.07,Cliente Nuevo
2,1,2014-02-01,18:43:12,1,Rodolfo,Bebida,Café americano,Bebida no Alcohol,0.07,Cliente Nuevo
3,1,2014-02-01,18:43:12,1,Rodolfo,Bebida,Te helado,Bebida no Alcohol,0.07,Cliente Nuevo
4,1,2014-02-01,18:43:12,1,Rodolfo,Comida,Pera Rostizada,Ensaladas,0.07,Cliente Nuevo

In [5]:
restdf.tail(5)

,Orden,Fecha,Hora de Cobro,Mesa,Atendió,Tipo,Producto,Categoria,Propina,Tipo de Cliente
30127,2500,2014-07-17,16:33:36,6,Joel,Comida,Mejillones Horneados,Entradas,0.1,Cliente Nuevo
30128,2500,2014-07-17,16:33:36,6,Joel,Comida,Brochetas Hawaiianas,Entradas,0.1,Cliente Nuevo
30129,2500,2014-07-17,16:33:36,6,Joel,Comida,Panela a la Leña,Entradas,0.1,Cliente Nuevo
30130,2500,2014-07-17,16:33:36,6,Joel,Comida,Vacío,Platos Fuertes,0.1,Cliente Nuevo
30131,2500,2014-07-17,16:33:36,6,Joel,Comida,Tacos Capeados,Tacos,0.1,Cliente Nuevo

In [6]:
preciosdf = pd.read_csv("Precios Restaurant.csv")

In [7]:
preciosdf.head(5)

    Producto               Tipo  Precio   Costo
0   Refresco  Bebida no Alcohol  $20.00  $16.00
1   Limonada  Bebida no Alcohol  $25.00  $20.00
2  Naranjada  Bebida no Alcohol  $25.00  $18.25
3     Tisana  Bebida no Alcohol  $25.00  $18.00
4  Te helado  Bebida no Alcohol  $25.00  $18.50

In [8]:
preciosdf["Precio"] = preciosdf["Precio"].str.replace("$","").astype("float") # corregimos str a float

In [9]:
preciosdf["Costo"] = preciosdf["Costo"].str.replace("$","").astype("float")# corregimos str a float

In [10]:
preciosdf.head(5)

    Producto               Tipo  Precio  Costo
0   Refresco  Bebida no Alcohol    20.0  16.00
1   Limonada  Bebida no Alcohol    25.0  20.00
2  Naranjada  Bebida no Alcohol    25.0  18.25
3     Tisana  Bebida no Alcohol    25.0  18.00
4  Te helado  Bebida no Alcohol    25.0  18.50

In [11]:
preciosdf["Ganancias"] = preciosdf["Precio"]-preciosdf["Costo"]

In [12]:
preciosdf.head(5)

    Producto               Tipo  Precio  Costo  Ganancias
0   Refresco  Bebida no Alcohol    20.0  16.00       4.00
1   Limonada  Bebida no Alcohol    25.0  20.00       5.00
2  Naranjada  Bebida no Alcohol    25.0  18.25       6.75
3     Tisana  Bebida no Alcohol    25.0  18.00       7.00
4  Te helado  Bebida no Alcohol    25.0  18.50       6.50

In [13]:
total_ganancias = sum(preciosdf["Ganancias"])
print(total_ganancias)

2596.86

In [14]:
restdf = restdf.drop("Hora de Cobro", axis=1)

In [15]:
restdf

,Orden,Fecha,Mesa,Atendió,Tipo,Producto,Categoria,Propina,Tipo de Cliente
0,1,2014-02-01,1,Rodolfo,Bebida,Tecate,Cervezas,0.07,Cliente Nuevo
1,1,2014-02-01,1,Rodolfo,Bebida,Tisana,Bebida no Alcohol,0.07,Cliente Nuevo
2,1,2014-02-01,1,Rodolfo,Bebida,Café americano,Bebida no Alcohol,0.07,Cliente Nuevo
3,1,2014-02-01,1,Rodolfo,Bebida,Te helado,Bebida no Alcohol,0.07,Cliente Nuevo
4,1,2014-02-01,1,Rodolfo,Comida,Pera Rostizada,Ensaladas,0.07,Cliente Nuevo
...,...,...,...,...,...,...,...,...,...
30127,2500,2014-07-17,6,Joel,Comida,Mejillones Horneados,Entradas,0.10,Cliente Nuevo
30128,2500,2014-07-17,6,Joel,Comida,Brochetas Hawaiianas,Entradas,0.10,Cliente Nuevo
30129,2500,2014-07-17,6,Joel,Comida,Panela a la Leña,Entradas,0.10,Cliente Nuevo
30130,2500,2014-07-17,6,Joel,Comida,Vacío,Platos Fuertes,0.10,Cliente Nuevo
30131,2500,2014-07-17,6,Joel,Comida,Tacos Capeados,Tacos,0.10,Cliente Nuevo

In [16]:
precioscarosdf = preciosdf[preciosdf["Precio"]>100]

In [18]:
precioscarosdf.head(30)

              Producto            Tipo  Precio   Costo  Ganancias
16              Vino 1           Vinos   587.0  422.64     164.36
17              Vino 2           Vinos   545.0  397.85     147.15
18              Vino 3           Vinos   670.0  415.40     254.60
19              Vino 4           Vinos   410.0  270.60     139.40
20              Vino 5           Vinos   758.0  553.34     204.66
21              Vino 6           Vinos   715.0  536.25     178.75
22              Vino 7           Vinos   748.0  501.16     246.84
23              Vino 8           Vinos   383.0  256.61     126.39
24             Vino 9            Vinos   647.0  478.78     168.22
25             Vino 10           Vinos   708.0  431.88     276.12
37     Pesto & Camarón          Pizzas   125.0  108.70      16.30
38      Salmón Ahumado          Pizzas   135.0  117.39      17.61
39           Del Cheff          Pizzas   135.0  117.39      17.61
40            Italiana          Pizzas   123.0  106.96      16.04
41           Margarita          Pizzas   105.0   91.30      13.70
42            Mexicana          Pizzas   115.0  100.00      15.00
43     Pollo al Pastor          Pizzas   115.0  100.00      15.00
44       Pizza Prímula          Pizzas   105.0   91.30      13.70
45            Tropical          Pizzas   125.0  108.70      16.30
57     Pollo Silvestre  Platos Fuertes   125.0  108.70      16.30
58     Margret de Pato  Platos Fuertes   198.0  172.17      25.83
59               Vacío  Platos Fuertes   164.0  142.61      21.39
60  Arrachera del Chef  Platos Fuertes   135.0  117.39      17.61
61     Salmón al Pesto  Platos Fuertes   174.0  151.30      22.70
62     Atún Encostrado  Platos Fuertes   178.0  154.78      23.22

In [20]:
preciosdf["Margen"]=np.where(preciosdf["Ganancias"]>100,"Alto","Bajo")

In [21]:
preciosdf.head()

    Producto               Tipo  Precio  Costo  Ganancias Margen
0   Refresco  Bebida no Alcohol    20.0  16.00       4.00   Bajo
1   Limonada  Bebida no Alcohol    25.0  20.00       5.00   Bajo
2  Naranjada  Bebida no Alcohol    25.0  18.25       6.75   Bajo
3     Tisana  Bebida no Alcohol    25.0  18.00       7.00   Bajo
4  Te helado  Bebida no Alcohol    25.0  18.50       6.50   Bajo

In [24]:
restdf = restdf.rename(columns={"Atendió":"Mesero"})

In [25]:
restdf

,Orden,Fecha,Mesa,Mesero,Tipo,Producto,Categoria,Propina,Tipo de Cliente
0,1,2014-02-01,1,Rodolfo,Bebida,Tecate,Cervezas,0.07,Cliente Nuevo
1,1,2014-02-01,1,Rodolfo,Bebida,Tisana,Bebida no Alcohol,0.07,Cliente Nuevo
2,1,2014-02-01,1,Rodolfo,Bebida,Café americano,Bebida no Alcohol,0.07,Cliente Nuevo
3,1,2014-02-01,1,Rodolfo,Bebida,Te helado,Bebida no Alcohol,0.07,Cliente Nuevo
4,1,2014-02-01,1,Rodolfo,Comida,Pera Rostizada,Ensaladas,0.07,Cliente Nuevo
...,...,...,...,...,...,...,...,...,...
30127,2500,2014-07-17,6,Joel,Comida,Mejillones Horneados,Entradas,0.10,Cliente Nuevo
30128,2500,2014-07-17,6,Joel,Comida,Brochetas Hawaiianas,Entradas,0.10,Cliente Nuevo
30129,2500,2014-07-17,6,Joel,Comida,Panela a la Leña,Entradas,0.10,Cliente Nuevo
30130,2500,2014-07-17,6,Joel,Comida,Vacío,Platos Fuertes,0.10,Cliente Nuevo
30131,2500,2014-07-17,6,Joel,Comida,Tacos Capeados,Tacos,0.10,Cliente Nuevo

In [26]:
restpreciodf = restdf.merge(preciosdf, on=["Producto"],how="left" )

In [28]:
restpreciodf.head()

,Orden,Fecha,Mesa,Mesero,Tipo_x,Producto,Categoria,Propina,Tipo de Cliente,Tipo_y,Precio,Costo,Ganancias,Margen
0,1,2014-02-01,1,Rodolfo,Bebida,Tecate,Cervezas,0.07,Cliente Nuevo,Cervezas,25.0,18.00,7.00,Bajo
1,1,2014-02-01,1,Rodolfo,Bebida,Tisana,Bebida no Alcohol,0.07,Cliente Nuevo,Bebida no Alcohol,25.0,18.00,7.00,Bajo
2,1,2014-02-01,1,Rodolfo,Bebida,Café americano,Bebida no Alcohol,0.07,Cliente Nuevo,Bebida no Alcohol,18.0,12.60,5.40,Bajo
3,1,2014-02-01,1,Rodolfo,Bebida,Te helado,Bebida no Alcohol,0.07,Cliente Nuevo,Bebida no Alcohol,25.0,18.50,6.50,Bajo
4,1,2014-02-01,1,Rodolfo,Comida,Pera Rostizada,Ensaladas,0.07,Cliente Nuevo,Ensaladas,89.0,77.39,11.61,Bajo

In [29]:
meseros = restdf["Mesero"]

In [30]:
meseros.head(5)

0    Rodolfo
1    Rodolfo
2    Rodolfo
3    Rodolfo
4    Rodolfo
Name: Mesero, dtype: object

In [34]:
meseros = meseros.drop_duplicates()

In [36]:
meseros.head(20)

0        Rodolfo
6       Mauricio
25          Joel
52     Valentina
69          Omar
103         Saul
131    Alejandro
226      Mariana
256      Ernesto
Name: Mesero, dtype: object

In [39]:
venxcat = pd.pivot_table(restpreciodf,values="Precio", index = "Categoria", aggfunc=np.sum) # Ventas por categoria

C:\Users\Almicar\AppData\Local\Temp\ipykernel_14460\3064849504.py:1: FutureWarning: The provided callable <function sum at 0x000001A0ED5FFBA0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  venxcat = pd.pivot_table(restpreciodf,values="Precio", index = "Categoria", aggfunc=np.sum) # Ventas por categoria

In [38]:
venxcat

                     Precio
Categoria
Bebida no Alcohol  194480.0
Cervezas           191595.0
Ensaladas          199209.0
Entradas           193511.0
Pastas              92367.0
Pizzas             385188.0
Platos Fuertes     353625.0
Postres             91509.0
Tacos               77346.0
Vinos              272799.0

In [40]:
ventxcatxtipo = pd.pivot_table(restpreciodf, values="Precio", index="Categoria",columns = "Tipo_x", aggfunc=np.sum)

C:\Users\Almicar\AppData\Local\Temp\ipykernel_14460\2659534991.py:1: FutureWarning: The provided callable <function sum at 0x000001A0ED5FFBA0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  ventxcatxtipo = pd.pivot_table(restpreciodf, values="Precio", index="Categoria",columns = "Tipo_x", aggfunc=np.sum)

In [42]:
ventxcatxtipo # Categoria y por tipo

Tipo_x               Bebida    Comida
Categoria
Bebida no Alcohol  194480.0       NaN
Cervezas           191595.0       NaN
Ensaladas               NaN  199209.0
Entradas                NaN  193511.0
Pastas                  NaN   92367.0
Pizzas                  NaN  385188.0
Platos Fuertes          NaN  353625.0
Postres                 NaN   91509.0
Tacos                   NaN   77346.0
Vinos              272799.0       NaN

In [46]:
venxtipocatxmesero = pd.pivot_table(restpreciodf,values="Precio", index=["Tipo_x","Categoria"],columns="Mesero",aggfunc=np.sum)

C:\Users\Almicar\AppData\Local\Temp\ipykernel_14460\1183391485.py:1: FutureWarning: The provided callable <function sum at 0x000001A0ED5FFBA0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  venxtipocatxmesero = pd.pivot_table(restpreciodf,values="Precio", index=["Tipo_x","Categoria"],columns="Mesero",aggfunc=np.sum)

In [50]:
venxtipocatxmesero

Mesero                    Alejandro  Ernesto     Joel  Mariana  Mauricio  \
Tipo_x Categoria
Bebida Bebida no Alcohol    21882.0  23244.0  22393.0  22514.0   18149.0
       Cervezas             22150.0  22870.0  22235.0  20595.0   17895.0
       Vinos                45957.0  38776.0  43333.0  25250.0       NaN
Comida Ensaladas            22756.0  21592.0  24344.0  22312.0   19644.0
       Entradas             21502.0  24555.0  22506.0  21255.0   19208.0
       Pastas               10374.0  11119.0  10602.0   8250.0    8481.0
       Pizzas               43626.0  47386.0  43325.0  46582.0   33872.0
       Platos Fuertes       37157.0  44278.0  44573.0  38887.0   29893.0
       Postres              10919.0   9780.0  11728.0  11000.0    7958.0
       Tacos                 8111.0   9036.0   8807.0   9457.0    7453.0

Mesero                       Omar  Rodolfo     Saul  Valentina
Tipo_x Categoria
Bebida Bebida no Alcohol  22870.0  21920.0  21532.0    19976.0
       Cervezas           22480.0  22385.0  20920.0    20065.0
       Vinos              31078.0  26233.0  35019.0    27153.0
Comida Ensaladas          24245.0  21567.0  22049.0    20700.0
       Entradas           22436.0  21707.0  21372.0    18970.0
       Pastas             11164.0  12187.0   9951.0    10239.0
       Pizzas             43771.0  40154.0  43319.0    43153.0
       Platos Fuertes     42607.0  44259.0  35199.0    36772.0
       Postres            10595.0  10391.0   9553.0     9585.0
       Tacos              10835.0   8741.0   8107.0     6799.0

In [51]:
ventpromxmesero = pd.pivot_table(restpreciodf, values="Precio", index="Mesero")

In [52]:
ventpromxmesero

              Precio
Mesero
Alejandro  71.263557
Ernesto    70.274270
Joel       71.405345
Mariana    66.874298
Mauricio   58.981495
Omar       67.943026
Rodolfo    66.844496
Saul       68.773402
Valentina  68.467116